name: Fallen's Docker Image
run-name: Fallen's Docker Image for ${{ github.event.inputs.koko_version }}

on:
  workflow_dispatch:
    inputs:
      koko_version:
        description: The version of koko used as the image tag, e.g. "v4.4.1-ce"
        type: string
        required: true

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fallenbreath
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fallenbreath/jumpserver-koko
          tags: |
            type=raw,${{ github.event.inputs.koko_version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: 'linux/amd64'
          file: ./Dockerfile
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
